### ISSUE TITLE
CSS needs fixed

### ISSUE THREAD

**Issue by GhzGarage** [qbcore-redm-framework/qbr-inventory#17]
Fresh build 1920x1080

![image](https://user-images.githubusercontent.com/57848836/158725338-a4a1849d-fda1-4f7a-b28d-4d7d7535ab9c.png)

**Comment by GttMone** [comment]
Is the issue resolved?

**Comment by DosKit** [comment]
Made Some CSS Adjustments should Be Corrected Once this is Merged. - https://github.com/qbcore-redm-framework/qbr-inventory/pull/30
